const items = [
    {
        id: '001',
        image: 'items/1.jpg',
        company: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.5,
            count: "14K",
        },
    },
    {
        id: '002',
        image: 'items/2.jpg',
        company: 'NOISE',
        item_name: 'Buds Aero Truly Wireless Earbuds',
        original_price: 2999,
        current_price: 899,
        discount_percentage: "₹ 2100 off",
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: "24K",
        },
    },
    {
        id: '003',
        image: 'items/3.jpg',
        company: 'NUEVOSDAMAS',
        item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.1,
            count: "249K",
        },
    },
    {
        id: '004',
        image: 'items/4.jpg',
        company: 'ADIDAS',
        item_name: 'Indian Cricket ODI Jersey',
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: "10K",
        },
    },
    {
        id: '005',
        image: 'items/5.jpg',
        company: 'Roadster',
        item_name: 'Pure Cotton T-shirt',
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: "35K",
        },
    },
    {
        id: '006',
        image: 'items/6.jpg',
        company: 'Nike',
        item_name: 'Men ReactX Running Shoes',
        original_price: 14995,
        current_price: 14995,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.9,
            count: "210K",
        },
    },
    {
        id: '007',
        image: 'items/7.jpg',
        company: 'The Indian Garage Co',
        item_name: 'Men Slim Fit Regular Shorts',
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        rating: {
            stars: 4.2,
            count: "388K",
        },
    },
    {
        id: '008',
        image: 'items/8.jpg',
        company: 'Nivea',
        item_name: 'Men Fresh Deodrant 150ml',
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: "52K",
        },
    },
    {
        id: '009',
        image: 'items/9.jpg',
        company: 'Roadster',
        item_name: 'Men Navy Solid Round Neck T-shirt',
        original_price: 499,
        current_price: 309,
        discount_percentage: 38,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4,
            count: "15.4K",
        },
    },
];